### Numpy Questions

**NumPy** is a powerful library for numerical computing in Python.  
It provides support for `arrays`, `matrices`, and many mathematical functions to operate on these data structures efficiently.  
It is widely used in *scientific computing*, *data analysis*, and *machine learning*.

In [1]:
import numpy as np

list1 = [1, 2, 3]
list2 = [4, 5, 6]
list3 = [7, 8, 9]

In [2]:
"1:Create a 3×3 square matrix in NumPy by static method."
matrix = np.array([list1, list2, list3])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
"2:Create a 3×3 square matrix in NumPy by giving user input."
matrix = np.array([[int(input(f"Enter the value for row {_+1}, column {j+1}: ")) for j in range(3)] for _ in range(3)])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
"3:Create two matrices of same order in NumPy using user input and show their addition."
matrix1 = np.array([[int(input(f"Enter the value for row {_+1}, column {j+1} of matrix 1: ")) for j in range(3)] for _ in range(3)])
matrix2 = np.array([[int(input(f"Enter the value for row {_+1}, column {j+1} of matrix 2: ")) for j in range(3)] for _ in range(3)])
print(f"Matrix 1: {matrix1}\nMatrix 2: {matrix2}")
matrix1 + matrix2

Matrix 1: [[9 8 7]
 [6 6 5]
 [4 3 3]]
Matrix 2: [[2 2 1]
 [2 3 5]
 [7 5 9]]


array([[11, 10,  8],
       [ 8,  9, 10],
       [11,  8, 12]])

In [5]:
"4:Create two matrices of same order by user input in NumPy and show their difference by subtracting them."
matrix1 = np.array([[int(input(f"Enter the value for row {_+1}, column {j+1} of matrix 1: ")) for j in range(3)] for _ in range(3)])
matrix2 = np.array([[int(input(f"Enter the value for row {_+1}, column {j+1} of matrix 2: ")) for j in range(3)] for _ in range(3)])
print(f"Matrix 1: {matrix1}\nMatrix 2: {matrix2}")
matrix1 - matrix2

Matrix 1: [[7 3 5]
 [7 2 5]
 [0 9 8]]
Matrix 2: [[7 6 5]
 [1 3 4]
 [5 6 3]]


array([[ 0, -3,  0],
       [ 6, -1,  1],
       [-5,  3,  5]])

In [6]:
"5:Create two matrices of same order in NumPy by user input and multiply them and show their output."
matrix1 = np.array([[int(input(f"Enter the value for row {_+1}, column {j+1} of matrix 1: ")) for j in range(3)] for _ in range(3)])
matrix2 = np.array([[int(input(f"Enter the value for row {_+1}, column {j+1} of matrix 2: ")) for j in range(3)] for _ in range(3)])
print(f"Matrix 1: {matrix1}\nMatrix 2: {matrix2}")
matrix1 @ matrix2


Matrix 1: [[8 6 5]
 [4 9 7]
 [5 3 5]]
Matrix 2: [[ 6  7  3]
 [ 5  4  1]
 [ 9 66 44]]


array([[123, 410, 250],
       [132, 526, 329],
       [ 90, 377, 238]])

In [7]:
"6:Write a program in NumPy to create a matrix and to print the upper triangle of the matrix."
np.triu(matrix)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [8]:
"7:Write a program in NumPy to create a matrix and to print the lower triangle of the matrix."
np.tril(matrix)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [9]:
"8:Write a program in NumPy to create a matrix and then to print it's transverse."
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [10]:
"9.Write a program in NumPy to create a matrix and then to print it's diagonal."
print(f"Matrix: {matrix}")
np.diag(matrix)

Matrix: [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 5, 9])

In [11]:
"10. Write a program in NumPy to create a matrix and to check whether a matrix is symmetric or not.( A symmetric matrix is equal to its transpose.)"
is_symmetric = np.array_equal(matrix, matrix.T)
print(f"Matrix:\n{matrix}")
print(f"Is the matrix symmetric? {is_symmetric}")

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Is the matrix symmetric? False
